# Generated by Django 5.0.6 on 2024-06-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutable',
            name='Inventory',
            field=models.IntegerField(max_length=5),
        ),
    ]
