# Generated by Django 5.0.6 on 2024-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menutable_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
