# Generated by Django 5.0.6 on 2024-06-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_no_of_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='Menu',
        ),
    ]
